# Generated by Django 5.0.13 on 2025-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_image_library_department_rack_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='file_bin',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
