# Generated by Django 5.0.13 on 2025-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_file_file_image_file_bin_image_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_bin',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_bin',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.TextField(),
        ),
    ]
