# Generated by Django 5.0.13 on 2025-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_file_bin_alter_file_file_context_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_bin',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_context',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file_bin',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.BinaryField(),
        ),
    ]
