# Generated by Django 5.0.13 on 2025-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_file_bin_file_file_remove_file_file_context_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
    ]
