# Generated by Django 5.0.13 on 2025-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_book_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
