# Generated by Django 5.0.13 on 2025-05-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rack'),
        ),
    ]
