# Generated by Django 5.0.13 on 2025-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_book_file_alter_book_image_alter_book_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extension',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
