# Generated by Django 5.0.13 on 2025-05-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ledger_isbn_alter_ledger_book_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isbn',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='log',
        ),
    ]
