# Generated by Django 5.0.13 on 2025-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ledger_is_overdue_alter_stock_isbn_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='approved_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='checkin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='checkout_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='rejected_date',
            field=models.DateField(null=True),
        ),
    ]
