# Generated by Django 5.0.13 on 2025-05-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_ledger_approved_date_alter_ledger_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rack'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.image'),
        ),
    ]
