# Generated by Django 5.0.13 on 2025-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_book_file_alter_book_image_alter_book_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
