# Generated by Django 5.0.13 on 2025-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ledger_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
